package com.pascoapp.wba02_android;

/**
 * Created by peter on 7/31/16.
 */

public class Actions {

    public enum ActionType {
        // Main screen actions
        SHOW_SCREEN,
        SET_ROUTE_RESOLUTIONS,

        BOUGHT_COURSES_REQUEST_INITIATED,
        BOUGHT_COURSES_REQUEST_SUCCESSFUL,
        BOUGHT_COURSES_REQUEST_FAILED,

        COURSE_REQUEST_INITIATED, COURSE_REQUEST_SUCCESSFUL, COURSE_REQUEST_FAILED, LIST_COURSE_REQUEST_INITIATED, LIST_COURSE_REQUEST_SUCCESSFUL, LIST_COURSE_REQUEST_FAILED,

        TEST_REQUEST_INITIATED, TEST_REQUEST_SUCCESSFUL, TEST_REQUEST_FAILED, LIST_TEST_REQUEST_INITIATED, LIST_TEST_REQUEST_SUCCESSFUL, LIST_TEST_REQUEST_FAILED,

        LECTURER_REQUEST_INITIATED, LECTURER_REQUEST_SUCCESSFUL, LECTURER_REQUEST_FAILED, LIST_LECTURER_REQUEST_INITIATED, LIST_LECTURER_REQUEST_SUCCESSFUL, LIST_LECTURER_REQUEST_FAILED,

        PROGRAMME_REQUEST_INITIATED, PROGRAMME_REQUEST_SUCCESSFUL, PROGRAMME_REQUEST_FAILED, LIST_PROGRAMME_REQUEST_INITIATED, LIST_PROGRAMME_REQUEST_SUCCESSFUL, LIST_PROGRAMME_REQUEST_FAILED,

        QUESTION_REQUEST_INITIATED, QUESTION_REQUEST_SUCCESSFUL, QUESTION_REQUEST_FAILED, LIST_QUESTION_REQUEST_INITIATED, LIST_QUESTION_REQUEST_SUCCESSFUL, LIST_QUESTION_REQUEST_FAILED,

        SCHOOL_REQUEST_INITIATED, SCHOOL_REQUEST_SUCCESSFUL, SCHOOL_REQUEST_FAILED, LIST_SCHOOL_REQUEST_INITIATED, LIST_SCHOOL_REQUEST_SUCCESSFUL, LIST_SCHOOL_REQUEST_FAILED,

        USER_REQUEST_INITIATED, USER_REQUEST_SUCCESSFUL, USER_REQUEST_FAILED, LIST_USER_REQUEST_INITIATED, LIST_USER_REQUEST_SUCCESSFUL, LIST_USER_REQUEST_FAILED,

        MESSAGE_REQUEST_INITIATED, MESSAGE_REQUEST_SUCCESSFUL, MESSAGE_REQUEST_FAILED, LIST_MESSAGE_REQUEST_INITIATED, LIST_MESSAGE_REQUEST_SUCCESSFUL, LIST_MESSAGE_REQUEST_FAILED,

    }

}
